# Generated by Django 4.1.6 on 2023-06-20 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poem',
            name='poet_author',
        ),
        migrations.RemoveField(
            model_name='poem',
            name='user_author',
        ),
        migrations.CreateModel(
            name='UserPoem',
            fields=[
                ('poem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.poem')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('home.poem',),
        ),
        migrations.CreateModel(
            name='ClassicPoem',
            fields=[
                ('poem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.poem')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poems', to='home.poem')),
            ],
            bases=('home.poem',),
        ),
    ]
