# Generated by Django 4.1.6 on 2023-05-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_poet_remove_poem_author_poem_user_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poet',
            name='poems',
            field=models.ManyToManyField(to='home.poem'),
        ),
    ]
