# Generated by Django 4.2.1 on 2023-06-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_poem_tags_alter_poem_user_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AddField(
            model_name='poet',
            name='photo',
            field=models.ImageField(null=True, upload_to='photo/'),
        ),
    ]
