# Generated by Django 4.1.6 on 2023-06-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_tags_options_poet_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poet',
            name='photo',
            field=models.ImageField(upload_to='photo/'),
        ),
    ]
