# Generated by Django 4.1.6 on 2023-06-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_avatar_alter_user_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='photo/default.png', upload_to='user/'),
        ),
    ]
